apt install -y gconf-service
apt install -y libasound2
apt install -y libatk1.0-0
apt install -y libatk-bridge2.0-0
apt install -y libc6
apt install -y libcairo2
apt install -y libcups2
apt install -y libdbus-1-3
apt install -y libexpat1
apt install -y libfontconfig1
apt install -y libgcc1
apt install -y libgconf-2-4
apt install -y libgdk-pixbuf2.0-0
apt install -y libglib2.0-0
apt install -y libgtk-3-0
apt install -y libnspr4
apt install -y libpango-1.0-0
apt install -y libpangocairo-1.0-0
apt install -y libstdc++6
apt install -y libx11-6
apt install -y libx11-xcb1
apt install -y libxcb1
apt install -y libxcomposite1
apt install -y libxcursor1
apt install -y libxdamage1
apt install -y libxext6
apt install -y libxfixes3
apt install -y libxi6
apt install -y libxrandr2
apt install -y libxrender1
apt install -y libxss1
apt install -y libxtst6
apt install -y ca-certificates
apt install -y fonts-liberation
apt install -y libappindicator1
apt install -y libnss3
apt install -y lsb-release
apt install -y xdg-utils
apt install -y wget
